#!/bin/bash
# author: rachpt
# version: v1.1
# date: 2018-04-17
# useage: set MS constent files as
#         paramters to this script.

#----------结果保存文本路径---------#
outPath='/home/rachpt/desktop/formatted.txt'

tempfile=`mktemp /tmp/const.XXXXXXXX`
tempPageElastic=`mktemp /tmp/elasticAnalysisPage.XXXXXXXX`

#----------参数量大于0-------------#
while [ $# != 0 ]; do

#-----------主循环开始-------------#
dos2unix "$1" &> /dev/null

#----------POST数据--------------#
matrixData=`grep -A 8 "Constants Cij"  "$1" | sed -n '4,$p' | awk 'BEGIN{OSF=""}{print "++++"$1"++++"$2"++++"$3"++++"$4"++++"$5"++++"$6}'`

#-----------提交计算--------------#
curl -s 'http://progs.coudert.name/elate' --data "matrix=$matrixData&sysname=test" > $tempPageElastic

#----------泊松比----------------#
minPoissonsRatio=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | awk '/Value/ {print $13}' | awk 'BEGIN{FS="[<|>]"} {print $5}'`
maxPoissonsRatio=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | awk '/Value/ {print $13}' | awk 'BEGIN{FS="[<|>]"} {print $9}'`

#----------泊松比坐标-------------#
minAxisPoissonsRatio1=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -B 2 "<td>Axis</td></tr>" | sed -n '1p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`
minAxisPoissonsRatio2=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -B 2 "Second axis" | sed -n '1p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`

maxAxisPoissonsRatio1=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -B 2 "<td>Axis</td></tr>" | sed -n '2p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`
maxAxisPoissonsRatio2=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -B 2 "Second axis" | sed -n '2p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`

#----------杨氏模量---------------#
minYoungsModulus=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | awk '/Value/ {print $2}'`
maxYoungsModulus=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | awk '/Value/ {print $4}'`

#----------杨氏模量坐标------------#
minAxisYoungsModulus=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -A 2 "<tr><td>Axis</td>" | sed -n '2p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`
maxAxisYoungsModulus=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -A 2 "<tr><td>Axis</td>" | sed -n '3p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`

#----------剪切模量---------------#
minShearModulus=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | awk '/Value/ {print $10}'`
maxShearModulus=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | awk '/Value/ {print $12}'`

#----------剪切模量坐标------------#
minAxisShearModulus1=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -B 4 "<td>Axis</td></tr>" | sed -n '1p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`
minAxisShearModulus2=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -B 4 "Second axis" | sed -n '1p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`

maxAxisShearModulus1=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -B 4 "<td>Axis</td></tr>" | sed -n '2p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`
maxAxisShearModulus2=`grep -A 24 "Variations of the elastic moduli" $tempPageElastic | grep -B 4 "Second axis" | sed -n '2p' | awk 'BEGIN{FS="[<|>]"} {printf "("$3","$5","$7")"}'`

#-----------格式化输出-------------#

sed -n '/+\/-/p' "$1" > $tempfile
bulkmodulus=`gawk '/=/ { print $4 }' $tempfile`
bulkmodulusErr=`gawk '/=/ { print $6 }' $tempfile`

for (( j = 4; j < 7; j = j + 2 ))
do
	if [ $j -eq 4 ]
	then
		echo -e "\n$bulkmodulus\t$bulkmodulusErr\t$minYoungsModulus\t$maxYoungsModulus\t$minShearModulus\t$maxShearModulus\t$minPoissonsRatio\t$maxPoissonsRatio\t\c"
		
	else
		echo -e "\t\t$minAxisYoungsModulus\t$maxAxisYoungsModulus\t$minAxisShearModulus1,$minAxisShearModulus2\t$maxAxisShearModulus1,$maxAxisShearModulus2\t$minAxisPoissonsRatio1,$minAxisPoissonsRatio2\t$maxAxisPoissonsRatio1,$maxAxisPoissonsRatio2\t\c"
	fi
		
	#-----打印Cij部分--------#
	for (( i = 1; i < 22; i++ ))
	do 
		cijTempName=`cat $tempfile | gawk -v circle=$j '$1 == loop {print $circle}' loop=$i`
	
		if [ $i -ge 2 ] && [ $i -le 6 ]
		then
			if [ -z $cijTempName ]
			then
				echo -e "-\t\c"
			else
				echo -e $cijTempName"\t\c"
			fi
		else
			if [ -z $cijTempName ]
			then
				echo -e "0\t\c"
			else
				echo -e $cijTempName"\t\c"
			fi
		fi
	done
	echo 
done | tee -a $outPath

#-----------主循环结束-------------#
shift  
done  

#-----------收尾--------------#
rm -f $tempfile $tempPageElastic
